# Generated by Django 4.1.1 on 2022-10-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_id_alter_comments_id_alter_issue_issue_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='Issue_posted_by',
        ),
    ]
