# Generated by Django 4.1.1 on 2022-10-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_issue_issue_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='Issue_posted_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
            preserve_default=False,
        ),
    ]
