# Generated by Django 4.1.1 on 2022-10-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_issue_issue_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
