# Generated by Django 4.1.1 on 2022-10-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Area', models.CharField(max_length=50)),
                ('PinCode', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Description', models.CharField(max_length=250)),
                ('Age', models.IntegerField()),
                ('Lives_in', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('Issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('Upvotes', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=250)),
                ('Title', models.CharField(max_length=100)),
                ('ImgUrl', models.CharField(max_length=200)),
                ('IssueCreatedTime', models.DateField(auto_now_add=True)),
                ('Issue_Loc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.location')),
                ('Issue_posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CreatedTime', models.DateField(auto_now_add=True)),
                ('CommentText', models.CharField(default='', max_length=300)),
                ('IssueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issue')),
                ('Posted_By', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.profile')),
            ],
        ),
    ]
