# Generated by Django 4.1.1 on 2022-10-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shaily'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shaily',
        ),
    ]
