# Generated by Django 4.1.1 on 2022-10-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_shaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ProfileImgUrl',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='auth0_id',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
