# Generated by Django 4.1.1 on 2022-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_profileimgurl_profile_auth0_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['auth0_id'], name='api_profile_auth0_i_aaa38d_idx'),
        ),
    ]
