# Generated by Django 4.1.1 on 2022-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_api_profile_auth0_i_aaa38d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='isResolved',
            field=models.BooleanField(default=False),
        ),
    ]
