# Generated by Django 4.1.1 on 2022-11-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_isauthority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('Manages_Loc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.location')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.profile')),
            ],
        ),
    ]
