name: CI/CD Pipeline

on:
  push:
    branches:
      - mybranch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Python Dependencies
        working-directory: backendServer
        run: |
          pip install -r requirements.txt  

      - name: Run Django Tests
        working-directory: backendServer
        run: |
          python manage.py test
      - name: Build React App
        working-directory: frontend
        run: |
         npm install
         npm run build -- --include-path=./src
